### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by lihongyi1234** [keijiro/UnitySioTest#1]
when i open this project in unity 2019.3.11, it reported a error named : Failed to resolve package :Registry configuration is invalid

![image](https://user-images.githubusercontent.com/36233282/83378531-83bcb780-a40b-11ea-9040-4add04e3f497.png)

**Comment by keijiro** [comment]
Is npmjs.com reachable from your computer? Are you using a proxy to access the internet?

**Comment by lihongyi1234** [comment]
npmjs.com reachable from my conputer ,i use a proxy to access the internet

**Comment by keijiro** [comment]
Could you check the "Configuring your proxy server" section on the following page?

https://docs.unity3d.com/Manual/upm-network.html

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.
