### ISSUE TITLE
Is it possible to record input stream to a wav file?

### ISSUE THREAD

**Issue by pajama** [keijiro/UnitySioTest#2]
I'm wondering if it's possible to record the input stream to a file. I would greatly appreciate any guidance on how to implement that.

Thanks so much for putting this together! This plugin is the only way I've been able to get audio input from the azure Kinect microphones into Unity.

**Comment by pajama** [comment]
I was able to cobble together some code to save a .wav file by concatenating InputStream.LastFrameWindow inside a coroutine loop.

**Comment by Hokore-Dev** [comment]
@pajama I'm utilizing LastFrameWindow and I'm having difficulty acquiring the correct .wav, is it possible to request a sample code by any chance?
