### ISSUE TITLE
It seems laggier than LASP

### ISSUE THREAD

**Issue by laurentopia** [keijiro/UnitySioTest#5]
Do you know why that could be? 
I thought it'd be due to jobs returning FT result a frame after but DftBuffer completes on the same frame...
Mystery.

**Comment by keijiro** [comment]
If you're comparing DFT with filter banks (LASP), yes. You can ask ChatGPT why FFT (DFT) is laggier than filter banks.

**Comment by laurentopia** [comment]
chatgpt is useless, I asked claude and I sorta get it: the lag for FFT = duraction of a wave at the lowest frequency that the FFT resolves too, whereas filter banks each frequency is resolved at each wave's duration: high frequency resolved at 1/hz and low frequency at their own. Is that it?
