### ISSUE TITLE
How can I record the audio as a File?

### ISSUE THREAD

**Issue by proDeveloper-chen** [keijiro/UnitySioTest#6]
Hello, I want to record the audio as a .wav, and after writing in the Header and the Format, how should I use the data from the LastFrameWindow ? Now I code it like this:

                WriteFileData(ref stream, ds.getStream().LastFrameWindow.ToArray());

                private void WriteFileData(ref MemoryStream stream, byte[] bytes)
                 {
                            // Write bytes to stream
                            WriteBytesToMemoryStream(ref stream, bytes, "DATA");
                 }

                //save the stream as a .wav
                byte[] bytes = stream.ToArray();
                Debug.Log("ByteSize:  " + bytes.Length + "  StreamSize:  " + stream.Length + "   count:   " + count);
                string filepath = string.Format("{0}/{1}.{2}", "recordings", DateTime.UtcNow.ToString("yyMMdd-HHmmss-fff"), "wav");
                Directory.CreateDirectory(Path.GetDirectoryName(filepath));
                File.WriteAllBytes(filepath, bytes);

I can get a .wav that can be played, but the content is just some noise, I don't know how to solve this.

**Comment by keijiro** [comment]
Your code snippet doesn’t include anything about the header, so I can only guess, but it seems likely that the header information is incorrect.

**Comment by proDeveloper-chen** [comment]
OK, thank your reply ,So does this mean that I can write the data in the LastFrameWindow  directly in the file if the Header is correct?

**Comment by keijiro** [comment]
I think so.

(I'm not sure because I haven't touched this project for +4 years.)

**Comment by keijiro** [comment]
I close this issue as answered. Please reopen it for further problems found in this project.

**Comment by proDeveloper-chen** [comment]
Thank you for your help! I finally solve this problem! The data in the LastFrameWindow should first be converted to float type, then converted to byte, I don't know how and why, but it just works. Thanks again!
